/**
 *
 * $Id$
 */
package org.talend.repository.model.hadoopcluster.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link org.talend.repository.model.hadoopcluster.HadoopClusterConnection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HadoopClusterConnectionValidator {
    boolean validate();

    boolean validateDistribution(String value);
    boolean validateDfVersion(String value);
    boolean validateUseCustomVersion(boolean value);
    boolean validateUseYarn(boolean value);
    boolean validateServer(String value);
    boolean validateNameNodeURI(String value);
    boolean validateJobTrackerURI(String value);
    boolean validateEnableKerberos(boolean value);
    boolean validatePrincipal(String value);
    boolean validateJtOrRmPrincipal(String value);
    boolean validateJobHistoryPrincipal(String value);
    boolean validateUserName(String value);
    boolean validateGroup(String value);
    boolean validateAuthMode(String value);
    boolean validateConnectionList(EList<String> value);
    boolean validateParameters(EMap<String, String> value);
    boolean validateUseKeytab(boolean value);
    boolean validateKeytabPrincipal(String value);
    boolean validateKeytab(String value);
    boolean validateHadoopProperties(String value);
    boolean validateRmScheduler(String value);
    boolean validateJobHistory(String value);
    boolean validateStagingDirectory(String value);
    boolean validateUseDNHost(boolean value);
    boolean validateUseCustomConfs(boolean value);
    boolean validateUseClouderaNavi(boolean value);
    boolean validateClouderaNaviUserName(String value);
    boolean validateClouderaNaviPassword(String value);
    boolean validateClouderaNaviUrl(String value);
    boolean validateClouderaNaviMetadataUrl(String value);
    boolean validateClouderaNaviClientUrl(String value);
    boolean validateClouderaDisableSSL(boolean value);

    boolean validateClouderaAutoCommit(boolean value);

    boolean validateClouderaDieNoError(boolean value);

    boolean validateUseClouderaDisableSSL(boolean value);
    boolean validateUseClouderaAutoCommit(boolean value);
    boolean validateUseClouderaDieNoError(boolean value);
}
