/**
 *
 * $Id$
 */
package org.talend.repository.model.hadoopcluster.validation;


/**
 * A sample validator interface for {@link org.talend.repository.model.hadoopcluster.HadoopSubConnection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HadoopSubConnectionValidator {
    boolean validate();

    boolean validateRelativeHadoopClusterId(String value);
    boolean validateHadoopProperties(String value);
}
