###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file et_EE.xml
# The source file version number was 1.48, generated on
# 2008/05/28 15:49:30.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::et_EE;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::et';

sub cldr_version { return "1\.6\.1" }

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::et_EE

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'et_EE' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Estonian Estonia.

=head1 DATA

This locale inherits from the L<DateTime::Locale::et> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  esmaspäev
  teisipäev
  kolmapäev
  neljapäev
  reede
  laupäev
  pühapäev

=head3 Abbreviated (format)

  E
  T
  K
  N
  R
  L
  P

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  esmaspäev
  teisipäev
  kolmapäev
  neljapäev
  reede
  laupäev
  pühapäev

=head3 Abbreviated (stand-alone)

  E
  T
  K
  N
  R
  L
  P

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  jaanuar
  veebruar
  märts
  aprill
  mai
  juuni
  juuli
  august
  september
  oktoober
  november
  detsember

=head3 Abbreviated (format)

  jaan
  veebr
  märts
  apr
  mai
  juuni
  juuli
  aug
  sept
  okt
  nov
  dets

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  jaanuar
  veebruar
  märts
  aprill
  mai
  juuni
  juuli
  august
  september
  oktoober
  november
  detsember

=head3 Abbreviated (stand-alone)

  jaan
  veebr
  märts
  apr
  mai
  juuni
  juuli
  aug
  sept
  okt
  nov
  dets

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  1. kvartal
  2. kvartal
  3. kvartal
  4. kvartal

=head3 Abbreviated (format)

  K1
  K2
  K3
  K4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1. kvartal
  2. kvartal
  3. kvartal
  4. kvartal

=head3 Abbreviated (stand-alone)

  K1
  K2
  K3
  K4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  enne meie aega
  meie aja järgi

=head3 Abbreviated

  e.m.a.
  m.a.j.

=head3 Narrow

  e.m.a.
  m.a.j.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = teisipäev, 5, veebruar 2008
   1995-12-22T09:05:02 = reede, 22, detsember 1995
  -0010-09-15T04:44:23 = laupäev, 15, september -010

=head3 Long

   2008-02-05T12:30:30 = 5 veebruar 2008
   1995-12-22T09:05:02 = 22 detsember 1995
  -0010-09-15T04:44:23 = 15 september -010

=head3 Medium

   2008-02-05T12:30:30 = 05.02.2008
   1995-12-22T09:05:02 = 22.12.1995
  -0010-09-15T04:44:23 = 15.09.-010

=head3 Short

   2008-02-05T12:30:30 = 05.02.8
   1995-12-22T09:05:02 = 22.12.95
  -0010-09-15T04:44:23 = 15.09.10

=head3 Default

   2008-02-05T12:30:30 = 05.02.2008
   1995-12-22T09:05:02 = 22.12.1995
  -0010-09-15T04:44:23 = 15.09.-010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 9:05:02 UTC
  -0010-09-15T04:44:23 = 4:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 9:05:02 UTC
  -0010-09-15T04:44:23 = 4:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 9:05:02
  -0010-09-15T04:44:23 = 4:44:23

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 9:05:02
  -0010-09-15T04:44:23 = 4:44:23

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = teisipäev, 5, veebruar 2008 12:30:30 UTC
   1995-12-22T09:05:02 = reede, 22, detsember 1995 9:05:02 UTC
  -0010-09-15T04:44:23 = laupäev, 15, september -010 4:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 5 veebruar 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 detsember 1995 9:05:02 UTC
  -0010-09-15T04:44:23 = 15 september -010 4:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 05.02.2008 12:30:30
   1995-12-22T09:05:02 = 22.12.1995 9:05:02
  -0010-09-15T04:44:23 = 15.09.-010 4:44:23

=head3 Short

   2008-02-05T12:30:30 = 05.02.8 12:30
   1995-12-22T09:05:02 = 22.12.95 9:05
  -0010-09-15T04:44:23 = 15.09.10 4:44

=head3 Default

   2008-02-05T12:30:30 = 05.02.2008 12:30:30
   1995-12-22T09:05:02 = 22.12.1995 9:05:02
  -0010-09-15T04:44:23 = 15.09.-010 4:44:23

=head2 Available Formats

=head3 Hm (H:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (E, M-d)

   2008-02-05T12:30:30 = T, 2-5
   1995-12-22T09:05:02 = R, 12-22
  -0010-09-15T04:44:23 = L, 9-15

=head3 MMM (LLL)

   2008-02-05T12:30:30 = veebr
   1995-12-22T09:05:02 = dets
  -0010-09-15T04:44:23 = sept

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = T veebr 5
   1995-12-22T09:05:02 = R dets 22
  -0010-09-15T04:44:23 = L sept 15

=head3 MMMMEd (E MMMM d)

   2008-02-05T12:30:30 = T veebruar 5
   1995-12-22T09:05:02 = R detsember 22
  -0010-09-15T04:44:23 = L september 15

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 veebruar
   1995-12-22T09:05:02 = 22 detsember
  -0010-09-15T04:44:23 = 15 september

=head3 MMMd (MMM d)

   2008-02-05T12:30:30 = veebr 5
   1995-12-22T09:05:02 = dets 22
  -0010-09-15T04:44:23 = sept 15

=head3 MMdd (dd.MM)

   2008-02-05T12:30:30 = 05.02
   1995-12-22T09:05:02 = 22.12
  -0010-09-15T04:44:23 = 15.09

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-09-15T04:44:23 = 9-15

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (yyyy-M)

   2008-02-05T12:30:30 = 2008-2
   1995-12-22T09:05:02 = 1995-12
  -0010-09-15T04:44:23 = -010-9

=head3 yMEd (EEE, yyyy-M-d)

   2008-02-05T12:30:30 = T, 2008-2-5
   1995-12-22T09:05:02 = R, 1995-12-22
  -0010-09-15T04:44:23 = L, -010-9-15

=head3 yMMM (yyyy MMM)

   2008-02-05T12:30:30 = 2008 veebr
   1995-12-22T09:05:02 = 1995 dets
  -0010-09-15T04:44:23 = -010 sept

=head3 yMMMEd (EEE, yyyy MMM d)

   2008-02-05T12:30:30 = T, 2008 veebr 5
   1995-12-22T09:05:02 = R, 1995 dets 22
  -0010-09-15T04:44:23 = L, -010 sept 15

=head3 yMMMM (yyyy MMMM)

   2008-02-05T12:30:30 = 2008 veebruar
   1995-12-22T09:05:02 = 1995 detsember
  -0010-09-15T04:44:23 = -010 september

=head3 yQ (yyyy Q)

   2008-02-05T12:30:30 = 2008 1
   1995-12-22T09:05:02 = 1995 4
  -0010-09-15T04:44:23 = -010 3

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 K1
   1995-12-22T09:05:02 = 1995 K4
  -0010-09-15T04:44:23 = -010 K3

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyyyMM (MM.yyyy)

   2008-02-05T12:30:30 = 02.2008
   1995-12-22T09:05:02 = 12.1995
  -0010-09-15T04:44:23 = 09.-010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = veebruar 2008
   1995-12-22T09:05:02 = detsember 1995
  -0010-09-15T04:44:23 = september -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

esmaspäev


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
