###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ka_GE.xml
# The source file version number was 1.35, generated on
# 2008/05/28 15:49:32.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ka_GE;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::ka';

sub cldr_version { return "1\.6\.1" }

{
    my $first_day_of_week = 7;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::ka_GE

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'ka_GE' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Georgian Georgia.

=head1 DATA

This locale inherits from the L<DateTime::Locale::ka> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  ორშაბათი
  სამშაბათი
  ოთხშაბათი
  ხუთშაბათი
  პარასკევი
  შაბათი
  კვირა

=head3 Abbreviated (format)

  ორშ
  სამ
  ოთხ
  ხუთ
  პარ
  შაბ
  კვი

=head3 Narrow (format)

  ო
  ს
  ო
  ხ
  პ
  შ
  კ

=head3 Wide (stand-alone)

  ორშაბათი
  სამშაბათი
  ოთხშაბათი
  ხუთშაბათი
  პარასკევი
  შაბათი
  კვირა

=head3 Abbreviated (stand-alone)

  ორშ
  სამ
  ოთხ
  ხუთ
  პარ
  შაბ
  კვი

=head3 Narrow (stand-alone)

  ო
  ს
  ო
  ხ
  პ
  შ
  კ

=head2 Months

=head3 Wide (format)

  იანვარი
  თებერვალი
  მარტი
  აპრილი
  მაისი
  ივნისი
  ივლისი
  აგვისტო
  სექტემბერი
  ოქტომბერი
  ნოემბერი
  დეკემბერი

=head3 Abbreviated (format)

  იან
  თებ
  მარ
  აპრ
  მაი
  ივნ
  ივლ
  აგვ
  სექ
  ოქტ
  ნოე
  დეკ

=head3 Narrow (format)

  ი
  თ
  მ
  ა
  მ
  ი
  ი
  ა
  ს
  ო
  ნ
  დ

=head3 Wide (stand-alone)

  იანვარი
  თებერვალი
  მარტი
  აპრილი
  მაისი
  ივნისი
  ივლისი
  აგვისტო
  სექტემბერი
  ოქტომბერი
  ნოემბერი
  დეკემბერი

=head3 Abbreviated (stand-alone)

  იან
  თებ
  მარ
  აპრ
  მაი
  ივნ
  ივლ
  აგვ
  სექ
  ოქტ
  ნოე
  დეკ

=head3 Narrow (stand-alone)

  ი
  თ
  მ
  ა
  მ
  ი
  ი
  ა
  ს
  ო
  ნ
  დ

=head2 Quarters

=head3 Wide (format)

  1-ლი კვარტალი
  მე-2 კვარტალი
  მე-3 კვარტალი
  მე-4 კვარტალი

=head3 Abbreviated (format)

  I კვ.
  II კვ.
  III კვ.
  IV კვ.

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  I კვარტალი
  II კვარტალი
  III კვარტალი
  IV კვარტალი

=head3 Abbreviated (stand-alone)

  I კვ.
  II კვ.
  III კვ.
  IV კვ.

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  ჩვენს წელთაღრიცხვამდე
  ჩვენი წელთაღრიცხვით

=head3 Abbreviated

  ჩვენს წელთაღრიცხვამდე
  ჩვენი წელთაღრიცხვით

=head3 Narrow

  ჩვენს წელთაღრიცხვამდე
  ჩვენი წელთაღრიცხვით

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = სამშაბათი, 2008 თებერვალი 05
   1995-12-22T09:05:02 = პარასკევი, 1995 დეკემბერი 22
  -0010-09-15T04:44:23 = შაბათი, -010 სექტემბერი 15

=head3 Long

   2008-02-05T12:30:30 = 2008 თებერვალი 5
   1995-12-22T09:05:02 = 1995 დეკემბერი 22
  -0010-09-15T04:44:23 = -010 სექტემბერი 15

=head3 Medium

   2008-02-05T12:30:30 = 2008 თებ 5
   1995-12-22T09:05:02 = 1995 დეკ 22
  -0010-09-15T04:44:23 = -010 სექ 15

=head3 Short

   2008-02-05T12:30:30 = 8/02/05
   1995-12-22T09:05:02 = 95/12/22
  -0010-09-15T04:44:23 = 10/09/15

=head3 Default

   2008-02-05T12:30:30 = 2008 თებ 5
   1995-12-22T09:05:02 = 1995 დეკ 22
  -0010-09-15T04:44:23 = -010 სექ 15

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-09-15T04:44:23 = 04:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-09-15T04:44:23 = 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = სამშაბათი, 2008 თებერვალი 05 12:30:30 UTC
   1995-12-22T09:05:02 = პარასკევი, 1995 დეკემბერი 22 09:05:02 UTC
  -0010-09-15T04:44:23 = შაბათი, -010 სექტემბერი 15 04:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 2008 თებერვალი 5 12:30:30 UTC
   1995-12-22T09:05:02 = 1995 დეკემბერი 22 09:05:02 UTC
  -0010-09-15T04:44:23 = -010 სექტემბერი 15 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008 თებ 5 12:30:30
   1995-12-22T09:05:02 = 1995 დეკ 22 09:05:02
  -0010-09-15T04:44:23 = -010 სექ 15 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 8/02/05 12:30
   1995-12-22T09:05:02 = 95/12/22 09:05
  -0010-09-15T04:44:23 = 10/09/15 04:44

=head3 Default

   2008-02-05T12:30:30 = 2008 თებ 5 12:30:30
   1995-12-22T09:05:02 = 1995 დეკ 22 09:05:02
  -0010-09-15T04:44:23 = -010 სექ 15 04:44:23

=head2 Available Formats

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Hm (H:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (E, M-d)

   2008-02-05T12:30:30 = სამ, 2-5
   1995-12-22T09:05:02 = პარ, 12-22
  -0010-09-15T04:44:23 = შაბ, 9-15

=head3 MMM (LLL)

   2008-02-05T12:30:30 = თებ
   1995-12-22T09:05:02 = დეკ
  -0010-09-15T04:44:23 = სექ

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = სამ თებ 5
   1995-12-22T09:05:02 = პარ დეკ 22
  -0010-09-15T04:44:23 = შაბ სექ 15

=head3 MMMMEd (E MMMM d)

   2008-02-05T12:30:30 = სამ თებერვალი 5
   1995-12-22T09:05:02 = პარ დეკემბერი 22
  -0010-09-15T04:44:23 = შაბ სექტემბერი 15

=head3 MMMMd (MMMM d)

   2008-02-05T12:30:30 = თებერვალი 5
   1995-12-22T09:05:02 = დეკემბერი 22
  -0010-09-15T04:44:23 = სექტემბერი 15

=head3 MMMd (MMM d)

   2008-02-05T12:30:30 = თებ 5
   1995-12-22T09:05:02 = დეკ 22
  -0010-09-15T04:44:23 = სექ 15

=head3 MMMdd (dd MMM)

   2008-02-05T12:30:30 = 05 თებ
   1995-12-22T09:05:02 = 22 დეკ
  -0010-09-15T04:44:23 = 15 სექ

=head3 MMdd (dd/MM)

   2008-02-05T12:30:30 = 05/02
   1995-12-22T09:05:02 = 22/12
  -0010-09-15T04:44:23 = 15/09

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-09-15T04:44:23 = 9-15

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 hhmm (hh:mm a)

   2008-02-05T12:30:30 = 12:30 საღამოს
   1995-12-22T09:05:02 = 09:05 დილის
  -0010-09-15T04:44:23 = 04:44 დილის

=head3 hhmmss (hh:mm:ss a)

   2008-02-05T12:30:30 = 12:30:30 საღამოს
   1995-12-22T09:05:02 = 09:05:02 დილის
  -0010-09-15T04:44:23 = 04:44:23 დილის

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (yyyy-M)

   2008-02-05T12:30:30 = 2008-2
   1995-12-22T09:05:02 = 1995-12
  -0010-09-15T04:44:23 = -010-9

=head3 yMEd (EEE, yyyy-M-d)

   2008-02-05T12:30:30 = სამ, 2008-2-5
   1995-12-22T09:05:02 = პარ, 1995-12-22
  -0010-09-15T04:44:23 = შაბ, -010-9-15

=head3 yMMM (yyyy MMM)

   2008-02-05T12:30:30 = 2008 თებ
   1995-12-22T09:05:02 = 1995 დეკ
  -0010-09-15T04:44:23 = -010 სექ

=head3 yMMMEd (EEE, yyyy MMM d)

   2008-02-05T12:30:30 = სამ, 2008 თებ 5
   1995-12-22T09:05:02 = პარ, 1995 დეკ 22
  -0010-09-15T04:44:23 = შაბ, -010 სექ 15

=head3 yMMMM (yyyy MMMM)

   2008-02-05T12:30:30 = 2008 თებერვალი
   1995-12-22T09:05:02 = 1995 დეკემბერი
  -0010-09-15T04:44:23 = -010 სექტემბერი

=head3 yQ (yyyy Q)

   2008-02-05T12:30:30 = 2008 1
   1995-12-22T09:05:02 = 1995 4
  -0010-09-15T04:44:23 = -010 3

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 I კვ.
   1995-12-22T09:05:02 = 1995 IV კვ.
  -0010-09-15T04:44:23 = -010 III კვ.

=head3 yyMM (MM/yy)

   2008-02-05T12:30:30 = 02/8
   1995-12-22T09:05:02 = 12/95
  -0010-09-15T04:44:23 = 09/10

=head3 yyMMMEEEd (EEE, d MMM, yy)

   2008-02-05T12:30:30 = სამ, 5 თებ, 8
   1995-12-22T09:05:02 = პარ, 22 დეკ, 95
  -0010-09-15T04:44:23 = შაბ, 15 სექ, 10

=head3 yyMMMd (d MMM, yy)

   2008-02-05T12:30:30 = 5 თებ, 8
   1995-12-22T09:05:02 = 22 დეკ, 95
  -0010-09-15T04:44:23 = 15 სექ, 10

=head3 yyMMdd (dd/MM/yy)

   2008-02-05T12:30:30 = 05/02/8
   1995-12-22T09:05:02 = 22/12/95
  -0010-09-15T04:44:23 = 15/09/10

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyQQQQ (QQQQ yy)

   2008-02-05T12:30:30 = 1-ლი კვარტალი 8
   1995-12-22T09:05:02 = მე-4 კვარტალი 95
  -0010-09-15T04:44:23 = მე-3 კვარტალი 10

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

კვირა


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
