###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file kn.xml
# The source file version number was 1.60, generated on
# 2008/06/15 08:09:47.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::kn;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::root';

sub cldr_version { return "1\.6\.1" }

{
    my $am_pm_abbreviated = [ "ಪೂರ್ವಾಹ್ನ", "ಅಪರಾಹ್ನ" ];
    sub am_pm_abbreviated { return $am_pm_abbreviated }
}
{
    my $date_format_full = "EEEE\ d\ MMMM\ yyyy";
    sub date_format_full { return $date_format_full }
}

{
    my $date_format_long = "d\ MMMM\ yyyy";
    sub date_format_long { return $date_format_long }
}

{
    my $date_format_medium = "dd\-MM\-yyyy";
    sub date_format_medium { return $date_format_medium }
}

{
    my $date_format_short = "d\-M\-yy";
    sub date_format_short { return $date_format_short }
}

{
    my $datetime_format = "\{1\}\ \{0\}";
    sub datetime_format { return $datetime_format }
}

{
    my $day_format_abbreviated = [ "ಸೋ\.", "ಮಂ\.", "ಬು\.", "ಗು\.", "ಶು\.", "ಶನಿ\.", "ರ\." ];
    sub day_format_abbreviated { return $day_format_abbreviated }
}

sub day_format_narrow { $_[0]->day_stand_alone_narrow() }

{
    my $day_format_wide = [ "ಸೋಮವಾರ", "ಮಂಗಳವಾರ", "ಬುಧವಾರ", "ಗುರುವಾರ", "ಶುಕ್ರವಾರ", "ಶನಿವಾರ", "ರವಿವಾರ" ];
    sub day_format_wide { return $day_format_wide }
}

sub day_stand_alone_abbreviated { $_[0]->day_format_abbreviated() }

{
    my $day_stand_alone_narrow = [ "2", "3", "4", "5", "6", "7", "1" ];
    sub day_stand_alone_narrow { return $day_stand_alone_narrow }
}

sub day_stand_alone_wide { $_[0]->day_format_wide() }

{
    my $era_abbreviated = [ "BCE", "CE" ];
    sub era_abbreviated { return $era_abbreviated }
}

sub era_narrow { $_[0]->era_abbreviated() }

{
    my $era_wide = [ "ಈಸಪೂವ೯\.", "ಸನ್\." ];
    sub era_wide { return $era_wide }
}
{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

{
    my $month_format_abbreviated = [ "ಜನವರೀ", "ಫೆಬ್ರವರೀ", "ಮಾರ್ಚ್", "ಎಪ್ರಿಲ್", "ಮೆ", "ಜೂನ್", "ಜುಲೈ", "ಆಗಸ್ಟ್", "ಸಪ್ಟೆಂಬರ್", "ಅಕ್ಟೋಬರ್", "ನವೆಂಬರ್", "ಡಿಸೆಂಬರ್" ];
    sub month_format_abbreviated { return $month_format_abbreviated }
}

sub month_format_narrow { $_[0]->month_stand_alone_narrow() }

{
    my $month_format_wide = [ "ಜನವರೀ", "ಫೆಬ್ರವರೀ", "ಮಾರ್ಚ್", "ಎಪ್ರಿಲ್", "ಮೆ", "ಜೂನ್", "ಜುಲೈ", "ಆಗಸ್ಟ್", "ಸಪ್ಟೆಂಬರ್", "ಅಕ್ಟೋಬರ್", "ನವೆಂಬರ್", "ಡಿಸೆಂಬರ್" ];
    sub month_format_wide { return $month_format_wide }
}

sub month_stand_alone_abbreviated { $_[0]->month_format_abbreviated() }

{
    my $month_stand_alone_narrow = [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" ];
    sub month_stand_alone_narrow { return $month_stand_alone_narrow }
}

sub month_stand_alone_wide { $_[0]->month_format_wide() }

{
    my $quarter_format_abbreviated = [ "Q1", "Q2", "Q3", "Q4" ];
    sub quarter_format_abbreviated { return $quarter_format_abbreviated }
}
{
    my $quarter_format_wide = [ "ಒಂದು\ \ 1", "ಎರಡು\ 2", "ಮೂರು\ 3", "ನಾಲೃಕ\ \ 4" ];
    sub quarter_format_wide { return $quarter_format_wide }
}

sub quarter_stand_alone_abbreviated { $_[0]->quarter_format_abbreviated() }


sub quarter_stand_alone_wide { $_[0]->quarter_format_wide() }

{
    my $time_format_full = "hh\:mm\:ss\ a\ v";
    sub time_format_full { return $time_format_full }
}

{
    my $time_format_long = "hh\:mm\:ss\ a\ z";
    sub time_format_long { return $time_format_long }
}

{
    my $time_format_medium = "hh\:mm\:ss\ a";
    sub time_format_medium { return $time_format_medium }
}

{
    my $time_format_short = "hh\:mm\ a";
    sub time_format_short { return $time_format_short }
}

{
    my $_format_for_MMMMd = "d\ MMMM";
    sub _format_for_MMMMd { return $_format_for_MMMMd }
}

{
    my $_format_for_MMdd = "dd\-MM";
    sub _format_for_MMdd { return $_format_for_MMdd }
}

{
    my $_format_for_yyQ = "Q\ yy";
    sub _format_for_yyQ { return $_format_for_yyQ }
}

{
    my $_format_for_yyyyMM = "MM\-yyyy";
    sub _format_for_yyyyMM { return $_format_for_yyyyMM }
}

{
    my $_format_for_yyyyMMMM = "MMMM\ yyyy";
    sub _format_for_yyyyMMMM { return $_format_for_yyyyMMMM }
}

{
    my $_available_formats =
        {
          "MMMMd" => "d\ MMMM",
          "MMdd" => "dd\-MM",
          "yyQ" => "Q\ yy",
          "yyyyMM" => "MM\-yyyy",
          "yyyyMMMM" => "MMMM\ yyyy"
        };
    sub _available_formats { return $_available_formats }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::kn

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'kn' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Kannada.

=head1 DATA

This locale inherits from the L<DateTime::Locale::root> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  ಸೋಮವಾರ
  ಮಂಗಳವಾರ
  ಬುಧವಾರ
  ಗುರುವಾರ
  ಶುಕ್ರವಾರ
  ಶನಿವಾರ
  ರವಿವಾರ

=head3 Abbreviated (format)

  ಸೋ.
  ಮಂ.
  ಬು.
  ಗು.
  ಶು.
  ಶನಿ.
  ರ.

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  ಸೋಮವಾರ
  ಮಂಗಳವಾರ
  ಬುಧವಾರ
  ಗುರುವಾರ
  ಶುಕ್ರವಾರ
  ಶನಿವಾರ
  ರವಿವಾರ

=head3 Abbreviated (stand-alone)

  ಸೋ.
  ಮಂ.
  ಬು.
  ಗು.
  ಶು.
  ಶನಿ.
  ರ.

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  ಜನವರೀ
  ಫೆಬ್ರವರೀ
  ಮಾರ್ಚ್
  ಎಪ್ರಿಲ್
  ಮೆ
  ಜೂನ್
  ಜುಲೈ
  ಆಗಸ್ಟ್
  ಸಪ್ಟೆಂಬರ್
  ಅಕ್ಟೋಬರ್
  ನವೆಂಬರ್
  ಡಿಸೆಂಬರ್

=head3 Abbreviated (format)

  ಜನವರೀ
  ಫೆಬ್ರವರೀ
  ಮಾರ್ಚ್
  ಎಪ್ರಿಲ್
  ಮೆ
  ಜೂನ್
  ಜುಲೈ
  ಆಗಸ್ಟ್
  ಸಪ್ಟೆಂಬರ್
  ಅಕ್ಟೋಬರ್
  ನವೆಂಬರ್
  ಡಿಸೆಂಬರ್

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  ಜನವರೀ
  ಫೆಬ್ರವರೀ
  ಮಾರ್ಚ್
  ಎಪ್ರಿಲ್
  ಮೆ
  ಜೂನ್
  ಜುಲೈ
  ಆಗಸ್ಟ್
  ಸಪ್ಟೆಂಬರ್
  ಅಕ್ಟೋಬರ್
  ನವೆಂಬರ್
  ಡಿಸೆಂಬರ್

=head3 Abbreviated (stand-alone)

  ಜನವರೀ
  ಫೆಬ್ರವರೀ
  ಮಾರ್ಚ್
  ಎಪ್ರಿಲ್
  ಮೆ
  ಜೂನ್
  ಜುಲೈ
  ಆಗಸ್ಟ್
  ಸಪ್ಟೆಂಬರ್
  ಅಕ್ಟೋಬರ್
  ನವೆಂಬರ್
  ಡಿಸೆಂಬರ್

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  ಒಂದು  1
  ಎರಡು 2
  ಮೂರು 3
  ನಾಲೃಕ  4

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  ಒಂದು  1
  ಎರಡು 2
  ಮೂರು 3
  ನಾಲೃಕ  4

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  ಈಸಪೂವ೯.
  ಸನ್.

=head3 Abbreviated

  BCE
  CE

=head3 Narrow

  BCE
  CE

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = ಮಂಗಳವಾರ 5 ಫೆಬ್ರವರೀ 2008
   1995-12-22T09:05:02 = ಶುಕ್ರವಾರ 22 ಡಿಸೆಂಬರ್ 1995
  -0010-09-15T04:44:23 = ಶನಿವಾರ 15 ಸಪ್ಟೆಂಬರ್ -010

=head3 Long

   2008-02-05T12:30:30 = 5 ಫೆಬ್ರವರೀ 2008
   1995-12-22T09:05:02 = 22 ಡಿಸೆಂಬರ್ 1995
  -0010-09-15T04:44:23 = 15 ಸಪ್ಟೆಂಬರ್ -010

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-09-15T04:44:23 = 15-09--010

=head3 Short

   2008-02-05T12:30:30 = 5-2-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-09-15T04:44:23 = 15-9-10

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-09-15T04:44:23 = 15-09--010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 ಅಪರಾಹ್ನ UTC
   1995-12-22T09:05:02 = 09:05:02 ಪೂರ್ವಾಹ್ನ UTC
  -0010-09-15T04:44:23 = 04:44:23 ಪೂರ್ವಾಹ್ನ UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 ಅಪರಾಹ್ನ UTC
   1995-12-22T09:05:02 = 09:05:02 ಪೂರ್ವಾಹ್ನ UTC
  -0010-09-15T04:44:23 = 04:44:23 ಪೂರ್ವಾಹ್ನ UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 09:05:02 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 04:44:23 ಪೂರ್ವಾಹ್ನ

=head3 Short

   2008-02-05T12:30:30 = 12:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 09:05 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 04:44 ಪೂರ್ವಾಹ್ನ

=head3 Default

   2008-02-05T12:30:30 = 12:30:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 09:05:02 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 04:44:23 ಪೂರ್ವಾಹ್ನ

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = ಮಂಗಳವಾರ 5 ಫೆಬ್ರವರೀ 2008 12:30:30 ಅಪರಾಹ್ನ UTC
   1995-12-22T09:05:02 = ಶುಕ್ರವಾರ 22 ಡಿಸೆಂಬರ್ 1995 09:05:02 ಪೂರ್ವಾಹ್ನ UTC
  -0010-09-15T04:44:23 = ಶನಿವಾರ 15 ಸಪ್ಟೆಂಬರ್ -010 04:44:23 ಪೂರ್ವಾಹ್ನ UTC

=head3 Long

   2008-02-05T12:30:30 = 5 ಫೆಬ್ರವರೀ 2008 12:30:30 ಅಪರಾಹ್ನ UTC
   1995-12-22T09:05:02 = 22 ಡಿಸೆಂಬರ್ 1995 09:05:02 ಪೂರ್ವಾಹ್ನ UTC
  -0010-09-15T04:44:23 = 15 ಸಪ್ಟೆಂಬರ್ -010 04:44:23 ಪೂರ್ವಾಹ್ನ UTC

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 22-12-1995 09:05:02 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 15-09--010 04:44:23 ಪೂರ್ವಾಹ್ನ

=head3 Short

   2008-02-05T12:30:30 = 5-2-8 12:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 22-12-95 09:05 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 15-9-10 04:44 ಪೂರ್ವಾಹ್ನ

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 ಅಪರಾಹ್ನ
   1995-12-22T09:05:02 = 22-12-1995 09:05:02 ಪೂರ್ವಾಹ್ನ
  -0010-09-15T04:44:23 = 15-09--010 04:44:23 ಪೂರ್ವಾಹ್ನ

=head2 Available Formats

=head3 Hm (H:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (E, M-d)

   2008-02-05T12:30:30 = ಮಂ., 2-5
   1995-12-22T09:05:02 = ಶು., 12-22
  -0010-09-15T04:44:23 = ಶನಿ., 9-15

=head3 MMM (LLL)

   2008-02-05T12:30:30 = ಫೆಬ್ರವರೀ
   1995-12-22T09:05:02 = ಡಿಸೆಂಬರ್
  -0010-09-15T04:44:23 = ಸಪ್ಟೆಂಬರ್

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = ಮಂ. ಫೆಬ್ರವರೀ 5
   1995-12-22T09:05:02 = ಶು. ಡಿಸೆಂಬರ್ 22
  -0010-09-15T04:44:23 = ಶನಿ. ಸಪ್ಟೆಂಬರ್ 15

=head3 MMMMEd (E MMMM d)

   2008-02-05T12:30:30 = ಮಂ. ಫೆಬ್ರವರೀ 5
   1995-12-22T09:05:02 = ಶು. ಡಿಸೆಂಬರ್ 22
  -0010-09-15T04:44:23 = ಶನಿ. ಸಪ್ಟೆಂಬರ್ 15

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 ಫೆಬ್ರವರೀ
   1995-12-22T09:05:02 = 22 ಡಿಸೆಂಬರ್
  -0010-09-15T04:44:23 = 15 ಸಪ್ಟೆಂಬರ್

=head3 MMMd (MMM d)

   2008-02-05T12:30:30 = ಫೆಬ್ರವರೀ 5
   1995-12-22T09:05:02 = ಡಿಸೆಂಬರ್ 22
  -0010-09-15T04:44:23 = ಸಪ್ಟೆಂಬರ್ 15

=head3 MMdd (dd-MM)

   2008-02-05T12:30:30 = 05-02
   1995-12-22T09:05:02 = 22-12
  -0010-09-15T04:44:23 = 15-09

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-09-15T04:44:23 = 9-15

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (yyyy-M)

   2008-02-05T12:30:30 = 2008-2
   1995-12-22T09:05:02 = 1995-12
  -0010-09-15T04:44:23 = -010-9

=head3 yMEd (EEE, yyyy-M-d)

   2008-02-05T12:30:30 = ಮಂ., 2008-2-5
   1995-12-22T09:05:02 = ಶು., 1995-12-22
  -0010-09-15T04:44:23 = ಶನಿ., -010-9-15

=head3 yMMM (yyyy MMM)

   2008-02-05T12:30:30 = 2008 ಫೆಬ್ರವರೀ
   1995-12-22T09:05:02 = 1995 ಡಿಸೆಂಬರ್
  -0010-09-15T04:44:23 = -010 ಸಪ್ಟೆಂಬರ್

=head3 yMMMEd (EEE, yyyy MMM d)

   2008-02-05T12:30:30 = ಮಂ., 2008 ಫೆಬ್ರವರೀ 5
   1995-12-22T09:05:02 = ಶು., 1995 ಡಿಸೆಂಬರ್ 22
  -0010-09-15T04:44:23 = ಶನಿ., -010 ಸಪ್ಟೆಂಬರ್ 15

=head3 yMMMM (yyyy MMMM)

   2008-02-05T12:30:30 = 2008 ಫೆಬ್ರವರೀ
   1995-12-22T09:05:02 = 1995 ಡಿಸೆಂಬರ್
  -0010-09-15T04:44:23 = -010 ಸಪ್ಟೆಂಬರ್

=head3 yQ (yyyy Q)

   2008-02-05T12:30:30 = 2008 1
   1995-12-22T09:05:02 = 1995 4
  -0010-09-15T04:44:23 = -010 3

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 Q1
   1995-12-22T09:05:02 = 1995 Q4
  -0010-09-15T04:44:23 = -010 Q3

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-09-15T04:44:23 = 09--010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = ಫೆಬ್ರವರೀ 2008
   1995-12-22T09:05:02 = ಡಿಸೆಂಬರ್ 1995
  -0010-09-15T04:44:23 = ಸಪ್ಟೆಂಬರ್ -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

No

=head3 Local first day of the week

ಸೋಮವಾರ


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
