###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file lv_LV.xml
# The source file version number was 1.46, generated on
# 2008/05/28 15:49:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::lv_LV;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::lv';

sub cldr_version { return "1\.6\.1" }

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::lv_LV

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'lv_LV' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Latvian Latvia.

=head1 DATA

This locale inherits from the L<DateTime::Locale::lv> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  pirmdiena
  otrdiena
  trešdiena
  ceturtdiena
  piektdiena
  sestdiena
  svētdiena

=head3 Abbreviated (format)

  P
  O
  T
  C
  Pk
  S
  Sv

=head3 Narrow (format)

  P
  O
  T
  C
  P
  S
  S

=head3 Wide (stand-alone)

  pirmdiena
  otrdiena
  trešdiena
  ceturtdiena
  piektdiena
  sestdiena
  svētdiena

=head3 Abbreviated (stand-alone)

  P
  O
  T
  C
  Pk
  S
  Sv

=head3 Narrow (stand-alone)

  P
  O
  T
  C
  P
  S
  S

=head2 Months

=head3 Wide (format)

  janvāris
  februāris
  marts
  aprīlis
  maijs
  jūnijs
  jūlijs
  augusts
  septembris
  oktobris
  novembris
  decembris

=head3 Abbreviated (format)

  Jan
  Feb
  Mar
  Apr
  Mai
  Jūn
  Jūl
  Aug
  Sep
  Okt
  Nov
  Dec

=head3 Narrow (format)

  J
  F
  M
  A
  M
  J
  J
  A
  S
  O
  N
  D

=head3 Wide (stand-alone)

  janvāris
  februāris
  marts
  aprīlis
  maijs
  jūnijs
  jūlijs
  augusts
  septembris
  oktobris
  novembris
  decembris

=head3 Abbreviated (stand-alone)

  Jan
  Feb
  Mar
  Apr
  Mai
  Jūn
  Jūl
  Aug
  Sep
  Okt
  Nov
  Dec

=head3 Narrow (stand-alone)

  J
  F
  M
  A
  M
  J
  J
  A
  S
  O
  N
  D

=head2 Quarters

=head3 Wide (format)

  1. ceturksnis
  2. ceturksnis
  3. ceturksnis
  4. ceturksnis

=head3 Abbreviated (format)

  C1
  C2
  C3
  C4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1. ceturksnis
  2. ceturksnis
  3. ceturksnis
  4. ceturksnis

=head3 Abbreviated (stand-alone)

  C1
  C2
  C3
  C4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  pirms mūsu ēras
  mūsu ērā

=head3 Abbreviated

  pmē
  mē

=head3 Narrow

  p.m.ē.
  m.ē.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = otrdiena, 2008. gada 5. februāris
   1995-12-22T09:05:02 = piektdiena, 1995. gada 22. decembris
  -0010-09-15T04:44:23 = sestdiena, -010. gada 15. septembris

=head3 Long

   2008-02-05T12:30:30 = 2008. gada 5. februāris
   1995-12-22T09:05:02 = 1995. gada 22. decembris
  -0010-09-15T04:44:23 = -010. gada 15. septembris

=head3 Medium

   2008-02-05T12:30:30 = 2008.5.2
   1995-12-22T09:05:02 = 1995.22.12
  -0010-09-15T04:44:23 = -010.15.9

=head3 Short

   2008-02-05T12:30:30 = 8.5.2
   1995-12-22T09:05:02 = 95.22.12
  -0010-09-15T04:44:23 = 10.15.9

=head3 Default

   2008-02-05T12:30:30 = 2008.5.2
   1995-12-22T09:05:02 = 1995.22.12
  -0010-09-15T04:44:23 = -010.15.9

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-09-15T04:44:23 = 04:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-09-15T04:44:23 = 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = otrdiena, 2008. gada 5. februāris 12:30:30 UTC
   1995-12-22T09:05:02 = piektdiena, 1995. gada 22. decembris 09:05:02 UTC
  -0010-09-15T04:44:23 = sestdiena, -010. gada 15. septembris 04:44:23 UTC

=head3 Long

   2008-02-05T12:30:30 = 2008. gada 5. februāris 12:30:30 UTC
   1995-12-22T09:05:02 = 1995. gada 22. decembris 09:05:02 UTC
  -0010-09-15T04:44:23 = -010. gada 15. septembris 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008.5.2 12:30:30
   1995-12-22T09:05:02 = 1995.22.12 09:05:02
  -0010-09-15T04:44:23 = -010.15.9 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 8.5.2 12:30
   1995-12-22T09:05:02 = 95.22.12 09:05
  -0010-09-15T04:44:23 = 10.15.9 04:44

=head3 Default

   2008-02-05T12:30:30 = 2008.5.2 12:30:30
   1995-12-22T09:05:02 = 1995.22.12 09:05:02
  -0010-09-15T04:44:23 = -010.15.9 04:44:23

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = O 5
   1995-12-22T09:05:02 = Pk 22
  -0010-09-15T04:44:23 = S 15

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-09-15T04:44:23 = 4

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Hm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (E, dd.MM)

   2008-02-05T12:30:30 = O, 05.02
   1995-12-22T09:05:02 = Pk, 22.12
  -0010-09-15T04:44:23 = S, 15.09

=head3 MMM (LLL)

   2008-02-05T12:30:30 = Feb
   1995-12-22T09:05:02 = Dec
  -0010-09-15T04:44:23 = Sep

=head3 MMMEd (E, d. MMM)

   2008-02-05T12:30:30 = O, 5. Feb
   1995-12-22T09:05:02 = Pk, 22. Dec
  -0010-09-15T04:44:23 = S, 15. Sep

=head3 MMMMEd (E, d. MMMM)

   2008-02-05T12:30:30 = O, 5. februāris
   1995-12-22T09:05:02 = Pk, 22. decembris
  -0010-09-15T04:44:23 = S, 15. septembris

=head3 MMMMd (d. MMMM)

   2008-02-05T12:30:30 = 5. februāris
   1995-12-22T09:05:02 = 22. decembris
  -0010-09-15T04:44:23 = 15. septembris

=head3 MMMd (d. MMM)

   2008-02-05T12:30:30 = 5. Feb
   1995-12-22T09:05:02 = 22. Dec
  -0010-09-15T04:44:23 = 15. Sep

=head3 Md (d.M)

   2008-02-05T12:30:30 = 5.2
   1995-12-22T09:05:02 = 22.12
  -0010-09-15T04:44:23 = 15.9

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (mm.yyyy)

   2008-02-05T12:30:30 = 30.2008
   1995-12-22T09:05:02 = 05.1995
  -0010-09-15T04:44:23 = 44.-010

=head3 yMEd (EEE, dd.mm.yyyy)

   2008-02-05T12:30:30 = O, 05.30.2008
   1995-12-22T09:05:02 = Pk, 22.05.1995
  -0010-09-15T04:44:23 = S, 15.44.-010

=head3 yMMM (yyyy. MMM)

   2008-02-05T12:30:30 = 2008. Feb
   1995-12-22T09:05:02 = 1995. Dec
  -0010-09-15T04:44:23 = -010. Sep

=head3 yMMMEd (EEE, dd. MMM, yyyy)

   2008-02-05T12:30:30 = O, 05. Feb, 2008
   1995-12-22T09:05:02 = Pk, 22. Dec, 1995
  -0010-09-15T04:44:23 = S, 15. Sep, -010

=head3 yMMMM (yyyy. MMMM)

   2008-02-05T12:30:30 = 2008. februāris
   1995-12-22T09:05:02 = 1995. decembris
  -0010-09-15T04:44:23 = -010. septembris

=head3 yQ (Q yyyy)

   2008-02-05T12:30:30 = 1 2008
   1995-12-22T09:05:02 = 4 1995
  -0010-09-15T04:44:23 = 3 -010

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 C1
   1995-12-22T09:05:02 = 1995 C4
  -0010-09-15T04:44:23 = -010 C3

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyyy (yyyy. 'g'.)

   2008-02-05T12:30:30 = 2008. g.
   1995-12-22T09:05:02 = 1995. g.
  -0010-09-15T04:44:23 = -010. g.

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

pirmdiena


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
