###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file pt_PT.xml
# The source file version number was 1.76, generated on
# 2008/06/26 03:47:58.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::pt_PT;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::pt';

sub cldr_version { return "1\.6\.1" }

{
    my $am_pm_abbreviated = [ "Antes\ do\ meio\-dia", "Depois\ do\ meio\-dia" ];
    sub am_pm_abbreviated { return $am_pm_abbreviated }
}
{
    my $date_format_medium = "yyyy\/MM\/dd";
    sub date_format_medium { return $date_format_medium }
}

{
    my $date_format_short = "yy\/MM\/dd";
    sub date_format_short { return $date_format_short }
}


sub era_abbreviated { $_[0]->era_wide() }

{
    my $era_wide = [ "a\.C\.", "d\.C\." ];
    sub era_wide { return $era_wide }
}
{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

{
    my $month_format_abbreviated = [ "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" ];
    sub month_format_abbreviated { return $month_format_abbreviated }
}

sub month_format_narrow { $_[0]->month_format_abbreviated() }

{
    my $month_format_wide = [ "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" ];
    sub month_format_wide { return $month_format_wide }
}

sub month_stand_alone_abbreviated { $_[0]->month_format_abbreviated() }


sub month_stand_alone_wide { $_[0]->month_format_wide() }


sub quarter_format_abbreviated { $_[0]->quarter_format_wide() }

{
    my $quarter_format_wide = [ "1\.º\ trimestre", "2\.º\ trimestre", "3\.º\ trimestre", "4\.º\ trimestre" ];
    sub quarter_format_wide { return $quarter_format_wide }
}

sub quarter_stand_alone_wide { $_[0]->quarter_format_wide() }

{
    my $time_format_full = "HH\'H\'mm\'m\'ss\'s\'\ v";
    sub time_format_full { return $time_format_full }
}

{
    my $_format_for_MMMEd = "E\ d\ MMM";
    sub _format_for_MMMEd { return $_format_for_MMMEd }
}

{
    my $_format_for_MMMMEd = "EEE\,\ d\ \'de\'\ MMMM";
    sub _format_for_MMMMEd { return $_format_for_MMMMEd }
}

{
    my $_format_for_MMMMd = "d\ \'de\'\ MMMM";
    sub _format_for_MMMMd { return $_format_for_MMMMd }
}

{
    my $_format_for_MMMd = "d\ \'de\'\ MMM";
    sub _format_for_MMMd { return $_format_for_MMMd }
}

{
    my $_format_for_Md = "d\-M";
    sub _format_for_Md { return $_format_for_Md }
}

{
    my $_format_for_yyMM = "MM\-yy";
    sub _format_for_yyMM { return $_format_for_yyMM }
}

{
    my $_format_for_yyyyMM = "MM\-yyyy";
    sub _format_for_yyyyMM { return $_format_for_yyyyMM }
}

{
    my $_available_formats =
        {
          "MMMEd" => "E\ d\ MMM",
          "MMMMEd" => "EEE\,\ d\ \'de\'\ MMMM",
          "MMMMd" => "d\ \'de\'\ MMMM",
          "MMMd" => "d\ \'de\'\ MMM",
          "Md" => "d\-M",
          "yyMM" => "MM\-yy",
          "yyyyMM" => "MM\-yyyy"
        };
    sub _available_formats { return $_available_formats }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::pt_PT

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'pt_PT' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Portuguese Portugal.

=head1 DATA

This locale inherits from the L<DateTime::Locale::pt> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  segunda-feira
  terça-feira
  quarta-feira
  quinta-feira
  sexta-feira
  sábado
  domingo

=head3 Abbreviated (format)

  seg
  ter
  qua
  qui
  sex
  sáb
  dom

=head3 Narrow (format)

  S
  T
  Q
  Q
  S
  S
  D

=head3 Wide (stand-alone)

  segunda-feira
  terça-feira
  quarta-feira
  quinta-feira
  sexta-feira
  sábado
  domingo

=head3 Abbreviated (stand-alone)

  seg
  ter
  qua
  qui
  sex
  sáb
  dom

=head3 Narrow (stand-alone)

  S
  T
  Q
  Q
  S
  S
  D

=head2 Months

=head3 Wide (format)

  Janeiro
  Fevereiro
  Março
  Abril
  Maio
  Junho
  Julho
  Agosto
  Setembro
  Outubro
  Novembro
  Dezembro

=head3 Abbreviated (format)

  Jan
  Fev
  Mar
  Abr
  Mai
  Jun
  Jul
  Ago
  Set
  Out
  Nov
  Dez

=head3 Narrow (format)

  Jan
  Fev
  Mar
  Abr
  Mai
  Jun
  Jul
  Ago
  Set
  Out
  Nov
  Dez

=head3 Wide (stand-alone)

  Janeiro
  Fevereiro
  Março
  Abril
  Maio
  Junho
  Julho
  Agosto
  Setembro
  Outubro
  Novembro
  Dezembro

=head3 Abbreviated (stand-alone)

  Jan
  Fev
  Mar
  Abr
  Mai
  Jun
  Jul
  Ago
  Set
  Out
  Nov
  Dez

=head3 Narrow (stand-alone)

  J
  F
  M
  A
  M
  J
  J
  A
  S
  O
  N
  D

=head2 Quarters

=head3 Wide (format)

  1.º trimestre
  2.º trimestre
  3.º trimestre
  4.º trimestre

=head3 Abbreviated (format)

  1.º trimestre
  2.º trimestre
  3.º trimestre
  4.º trimestre

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1.º trimestre
  2.º trimestre
  3.º trimestre
  4.º trimestre

=head3 Abbreviated (stand-alone)

  1.º trimestre
  2.º trimestre
  3.º trimestre
  4.º trimestre

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  a.C.
  d.C.

=head3 Abbreviated

  a.C.
  d.C.

=head3 Narrow

  a.C.
  d.C.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = terça-feira, 5 de Fevereiro de 2008
   1995-12-22T09:05:02 = sexta-feira, 22 de Dezembro de 1995
  -0010-09-15T04:44:23 = sábado, 15 de Setembro de -010

=head3 Long

   2008-02-05T12:30:30 = 5 de Fevereiro de 2008
   1995-12-22T09:05:02 = 22 de Dezembro de 1995
  -0010-09-15T04:44:23 = 15 de Setembro de -010

=head3 Medium

   2008-02-05T12:30:30 = 2008/02/05
   1995-12-22T09:05:02 = 1995/12/22
  -0010-09-15T04:44:23 = -010/09/15

=head3 Short

   2008-02-05T12:30:30 = 8/02/05
   1995-12-22T09:05:02 = 95/12/22
  -0010-09-15T04:44:23 = 10/09/15

=head3 Default

   2008-02-05T12:30:30 = 2008/02/05
   1995-12-22T09:05:02 = 1995/12/22
  -0010-09-15T04:44:23 = -010/09/15

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12H30m30s UTC
   1995-12-22T09:05:02 = 09H05m02s UTC
  -0010-09-15T04:44:23 = 04H44m23s UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-09-15T04:44:23 = 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = terça-feira, 5 de Fevereiro de 2008 12H30m30s UTC
   1995-12-22T09:05:02 = sexta-feira, 22 de Dezembro de 1995 09H05m02s UTC
  -0010-09-15T04:44:23 = sábado, 15 de Setembro de -010 04H44m23s UTC

=head3 Long

   2008-02-05T12:30:30 = 5 de Fevereiro de 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 de Dezembro de 1995 09:05:02 UTC
  -0010-09-15T04:44:23 = 15 de Setembro de -010 04:44:23 UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008/02/05 12:30:30
   1995-12-22T09:05:02 = 1995/12/22 09:05:02
  -0010-09-15T04:44:23 = -010/09/15 04:44:23

=head3 Short

   2008-02-05T12:30:30 = 8/02/05 12:30
   1995-12-22T09:05:02 = 95/12/22 09:05
  -0010-09-15T04:44:23 = 10/09/15 04:44

=head3 Default

   2008-02-05T12:30:30 = 2008/02/05 12:30:30
   1995-12-22T09:05:02 = 1995/12/22 09:05:02
  -0010-09-15T04:44:23 = -010/09/15 04:44:23

=head2 Available Formats

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-09-15T04:44:23 = 04:44

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-09-15T04:44:23 = 04:44:23

=head3 Hm (H:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (EEE, dd/MM)

   2008-02-05T12:30:30 = ter, 05/02
   1995-12-22T09:05:02 = sex, 22/12
  -0010-09-15T04:44:23 = sáb, 15/09

=head3 MMM (LLL)

   2008-02-05T12:30:30 = Fev
   1995-12-22T09:05:02 = Dez
  -0010-09-15T04:44:23 = Set

=head3 MMMEd (E d MMM)

   2008-02-05T12:30:30 = ter 5 Fev
   1995-12-22T09:05:02 = sex 22 Dez
  -0010-09-15T04:44:23 = sáb 15 Set

=head3 MMMMEd (EEE, d 'de' MMMM)

   2008-02-05T12:30:30 = ter, 5 de Fevereiro
   1995-12-22T09:05:02 = sex, 22 de Dezembro
  -0010-09-15T04:44:23 = sáb, 15 de Setembro

=head3 MMMMd (d 'de' MMMM)

   2008-02-05T12:30:30 = 5 de Fevereiro
   1995-12-22T09:05:02 = 22 de Dezembro
  -0010-09-15T04:44:23 = 15 de Setembro

=head3 MMMd (d 'de' MMM)

   2008-02-05T12:30:30 = 5 de Fev
   1995-12-22T09:05:02 = 22 de Dez
  -0010-09-15T04:44:23 = 15 de Set

=head3 MMdd (dd/MM)

   2008-02-05T12:30:30 = 05/02
   1995-12-22T09:05:02 = 22/12
  -0010-09-15T04:44:23 = 15/09

=head3 Md (d-M)

   2008-02-05T12:30:30 = 5-2
   1995-12-22T09:05:02 = 22-12
  -0010-09-15T04:44:23 = 15-9

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (MM/yyyy)

   2008-02-05T12:30:30 = 02/2008
   1995-12-22T09:05:02 = 12/1995
  -0010-09-15T04:44:23 = 09/-010

=head3 yMEd (EEE, dd/MM/yyyy)

   2008-02-05T12:30:30 = ter, 05/02/2008
   1995-12-22T09:05:02 = sex, 22/12/1995
  -0010-09-15T04:44:23 = sáb, 15/09/-010

=head3 yMMM (MMM 'de' yyyy)

   2008-02-05T12:30:30 = Fev de 2008
   1995-12-22T09:05:02 = Dez de 1995
  -0010-09-15T04:44:23 = Set de -010

=head3 yMMMEd (EEE, d 'de' MMM 'de' yyyy)

   2008-02-05T12:30:30 = ter, 5 de Fev de 2008
   1995-12-22T09:05:02 = sex, 22 de Dez de 1995
  -0010-09-15T04:44:23 = sáb, 15 de Set de -010

=head3 yMMMM (MMMM 'de' yyyy)

   2008-02-05T12:30:30 = Fevereiro de 2008
   1995-12-22T09:05:02 = Dezembro de 1995
  -0010-09-15T04:44:23 = Setembro de -010

=head3 yQ (yyyy Q)

   2008-02-05T12:30:30 = 2008 1
   1995-12-22T09:05:02 = 1995 4
  -0010-09-15T04:44:23 = -010 3

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 1.º trimestre
   1995-12-22T09:05:02 = 1995 4.º trimestre
  -0010-09-15T04:44:23 = -010 3.º trimestre

=head3 yyMM (MM-yy)

   2008-02-05T12:30:30 = 02-8
   1995-12-22T09:05:02 = 12-95
  -0010-09-15T04:44:23 = 09-10

=head3 yyMMM (MMM yy)

   2008-02-05T12:30:30 = Fev 8
   1995-12-22T09:05:02 = Dez 95
  -0010-09-15T04:44:23 = Set 10

=head3 yyMMMEEEd (EEE, d 'de' MMM 'de' yy)

   2008-02-05T12:30:30 = ter, 5 de Fev de 8
   1995-12-22T09:05:02 = sex, 22 de Dez de 95
  -0010-09-15T04:44:23 = sáb, 15 de Set de 10

=head3 yyMMMd (d 'de' MMM 'de' yy)

   2008-02-05T12:30:30 = 5 de Fev de 8
   1995-12-22T09:05:02 = 22 de Dez de 95
  -0010-09-15T04:44:23 = 15 de Set de 10

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-09-15T04:44:23 = 09--010

=head3 yyyyMMM (MMM 'de' yyyy)

   2008-02-05T12:30:30 = Fev de 2008
   1995-12-22T09:05:02 = Dez de 1995
  -0010-09-15T04:44:23 = Set de -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

segunda-feira


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
