###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ta_IN.xml
# The source file version number was 1.55, generated on
# 2008/05/28 15:49:36.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ta_IN;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::ta';

sub cldr_version { return "1\.6\.1" }

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::ta_IN

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'ta_IN' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Tamil India.

=head1 DATA

This locale inherits from the L<DateTime::Locale::ta> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  திங்கள்
  செவ்வாய்
  புதன்
  வியாழன்
  வெள்ளி
  சனி
  ஞாயிறு

=head3 Abbreviated (format)

  தி
  செ
  பு
  வி
  வெ
  ச
  ஞா

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  திங்கள்
  செவ்வாய்
  புதன்
  வியாழன்
  வெள்ளி
  சனி
  ஞாயிறு

=head3 Abbreviated (stand-alone)

  தி
  செ
  பு
  வி
  வெ
  ச
  ஞா

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  ஜனவரி
  பிப்ரவரி
  மார்ச்
  ஏப்ரல்
  மே
  ஜூன்
  ஜூலை
  ஆகஸ்ட்
  செப்டம்பர்
  அக்டோபர்
  நவம்பர்
  டிசம்பர்

=head3 Abbreviated (format)

  ஜன.
  பிப்.
  மார்.
  ஏப்.
  மே
  ஜூன்
  ஜூலை
  ஆக.
  செப்.
  அக்.
  நவ.
  டிச.

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  ஜனவரி
  பிப்ரவரி
  மார்ச்
  ஏப்ரல்
  மே
  ஜூன்
  ஜூலை
  ஆகஸ்ட்
  செப்டம்பர்
  அக்டோபர்
  நவம்பர்
  டிசம்பர்

=head3 Abbreviated (stand-alone)

  ஜன.
  பிப்.
  மார்.
  ஏப்.
  மே
  ஜூன்
  ஜூலை
  ஆக.
  செப்.
  அக்.
  நவ.
  டிச.

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  1ஆம் காலாண்டு
  2ஆம் காலாண்டு
  3ஆம் காலாண்டு
  4ஆம் காலாண்டு

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1ஆம் காலாண்டு
  2ஆம் காலாண்டு
  3ஆம் காலாண்டு
  4ஆம் காலாண்டு

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  கிறிஸ்துவுக்கு முன்
  அனோ டோமினி

=head3 Abbreviated

  கிமு
  கிபி

=head3 Narrow

  கிமு
  கிபி

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = செவ்வாய் 5 பிப்ரவரி 2008
   1995-12-22T09:05:02 = வெள்ளி 22 டிசம்பர் 1995
  -0010-09-15T04:44:23 = சனி 15 செப்டம்பர் -010

=head3 Long

   2008-02-05T12:30:30 = 5 பிப்ரவரி 2008
   1995-12-22T09:05:02 = 22 டிசம்பர் 1995
  -0010-09-15T04:44:23 = 15 செப்டம்பர் -010

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-09-15T04:44:23 = 15-09--010

=head3 Short

   2008-02-05T12:30:30 = 5-2-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-09-15T04:44:23 = 15-9-10

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-09-15T04:44:23 = 15-09--010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 மாலை UTC
   1995-12-22T09:05:02 = 9:05:02 காலை UTC
  -0010-09-15T04:44:23 = 4:44:23 காலை UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 மாலை UTC
   1995-12-22T09:05:02 = 9:05:02 காலை UTC
  -0010-09-15T04:44:23 = 4:44:23 காலை UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30 மாலை
   1995-12-22T09:05:02 = 9:05:02 காலை
  -0010-09-15T04:44:23 = 4:44:23 காலை

=head3 Short

   2008-02-05T12:30:30 = 12:30 மாலை
   1995-12-22T09:05:02 = 9:05 காலை
  -0010-09-15T04:44:23 = 4:44 காலை

=head3 Default

   2008-02-05T12:30:30 = 12:30:30 மாலை
   1995-12-22T09:05:02 = 9:05:02 காலை
  -0010-09-15T04:44:23 = 4:44:23 காலை

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = செவ்வாய் 5 பிப்ரவரி 2008 12:30:30 மாலை UTC
   1995-12-22T09:05:02 = வெள்ளி 22 டிசம்பர் 1995 9:05:02 காலை UTC
  -0010-09-15T04:44:23 = சனி 15 செப்டம்பர் -010 4:44:23 காலை UTC

=head3 Long

   2008-02-05T12:30:30 = 5 பிப்ரவரி 2008 12:30:30 மாலை UTC
   1995-12-22T09:05:02 = 22 டிசம்பர் 1995 9:05:02 காலை UTC
  -0010-09-15T04:44:23 = 15 செப்டம்பர் -010 4:44:23 காலை UTC

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 மாலை
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 காலை
  -0010-09-15T04:44:23 = 15-09--010 4:44:23 காலை

=head3 Short

   2008-02-05T12:30:30 = 5-2-8 12:30 மாலை
   1995-12-22T09:05:02 = 22-12-95 9:05 காலை
  -0010-09-15T04:44:23 = 15-9-10 4:44 காலை

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 மாலை
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 காலை
  -0010-09-15T04:44:23 = 15-09--010 4:44:23 காலை

=head2 Available Formats

=head3 Hm (H:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 9:05
  -0010-09-15T04:44:23 = 4:44

=head3 M (L)

   2008-02-05T12:30:30 = 2
   1995-12-22T09:05:02 = 12
  -0010-09-15T04:44:23 = 9

=head3 MEd (E, M-d)

   2008-02-05T12:30:30 = செ, 2-5
   1995-12-22T09:05:02 = வெ, 12-22
  -0010-09-15T04:44:23 = ச, 9-15

=head3 MMM (LLL)

   2008-02-05T12:30:30 = பிப்.
   1995-12-22T09:05:02 = டிச.
  -0010-09-15T04:44:23 = செப்.

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = செ பிப். 5
   1995-12-22T09:05:02 = வெ டிச. 22
  -0010-09-15T04:44:23 = ச செப். 15

=head3 MMMMEd (E MMMM d)

   2008-02-05T12:30:30 = செ பிப்ரவரி 5
   1995-12-22T09:05:02 = வெ டிசம்பர் 22
  -0010-09-15T04:44:23 = ச செப்டம்பர் 15

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 பிப்ரவரி
   1995-12-22T09:05:02 = 22 டிசம்பர்
  -0010-09-15T04:44:23 = 15 செப்டம்பர்

=head3 MMMd (MMM d)

   2008-02-05T12:30:30 = பிப். 5
   1995-12-22T09:05:02 = டிச. 22
  -0010-09-15T04:44:23 = செப். 15

=head3 MMdd (dd-MM)

   2008-02-05T12:30:30 = 05-02
   1995-12-22T09:05:02 = 22-12
  -0010-09-15T04:44:23 = 15-09

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-09-15T04:44:23 = 9-15

=head3 d (d)

   2008-02-05T12:30:30 = 5
   1995-12-22T09:05:02 = 22
  -0010-09-15T04:44:23 = 15

=head3 ms (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-09-15T04:44:23 = 44:23

=head3 y (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-09-15T04:44:23 = -010

=head3 yM (yyyy-M)

   2008-02-05T12:30:30 = 2008-2
   1995-12-22T09:05:02 = 1995-12
  -0010-09-15T04:44:23 = -010-9

=head3 yMEd (EEE, yyyy-M-d)

   2008-02-05T12:30:30 = செ, 2008-2-5
   1995-12-22T09:05:02 = வெ, 1995-12-22
  -0010-09-15T04:44:23 = ச, -010-9-15

=head3 yMMM (yyyy MMM)

   2008-02-05T12:30:30 = 2008 பிப்.
   1995-12-22T09:05:02 = 1995 டிச.
  -0010-09-15T04:44:23 = -010 செப்.

=head3 yMMMEd (EEE, yyyy MMM d)

   2008-02-05T12:30:30 = செ, 2008 பிப். 5
   1995-12-22T09:05:02 = வெ, 1995 டிச. 22
  -0010-09-15T04:44:23 = ச, -010 செப். 15

=head3 yMMMM (yyyy MMMM)

   2008-02-05T12:30:30 = 2008 பிப்ரவரி
   1995-12-22T09:05:02 = 1995 டிசம்பர்
  -0010-09-15T04:44:23 = -010 செப்டம்பர்

=head3 yQ (yyyy Q)

   2008-02-05T12:30:30 = 2008 1
   1995-12-22T09:05:02 = 1995 4
  -0010-09-15T04:44:23 = -010 3

=head3 yQQQ (yyyy QQQ)

   2008-02-05T12:30:30 = 2008 Q1
   1995-12-22T09:05:02 = 1995 Q4
  -0010-09-15T04:44:23 = -010 Q3

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-09-15T04:44:23 = 3 10

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-09-15T04:44:23 = 09--010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = பிப்ரவரி 2008
   1995-12-22T09:05:02 = டிசம்பர் 1995
  -0010-09-15T04:44:23 = செப்டம்பர் -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

No

=head3 Local first day of the week

திங்கள்


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
