$dbd_oracle_mm_opts = {
                        'NAME' => 'DBD::Oracle',
                        'INC' => '-IC:/instantclient_11_1/sdk/include -IC:/instantclient_11_1/rdbms/demo -IC:\\strawberry\\perl\\site\\lib\\auto\\DBI',
                        'LIBS' => [
                                    '-LC:/strawberry/cpan/build/DBD-Oracle-1.23-7X_huJ -loci'
                                  ],
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'DIR' => [],
                        'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"11.1.0.7\\"',
                        'dist' => {
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist',
                                    'COMPRESS' => 'gzip -v9',
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir',
                                    'SUFFIX' => 'gz'
                                  },
                        'OBJECT' => '$(O_FILES)',
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*'
                                   },
                        'EXE_FILES' => [
                                         'ora_explain'
                                       ],
                        'ABSTRACT_FROM' => 'Oracle.pm',
                        'VERSION_FROM' => 'Oracle.pm',
                        'PREREQ_PM' => {
                                         'DBI' => '1.51'
                                       }
                      };
$dbd_oracle_mm_self = bless( {
                               'MM_Win32_VERSION' => '6.48',
                               'BSLOADLIBS' => '',
                               'ECHO_N' => '$(ABSPERLRUN)  -e "print qq{{@ARGV}" --',
                               'BOOTDEP' => '',
                               'INSTALLSITESCRIPT' => '$(INSTALLSCRIPT)',
                               'CCDLFLAGS' => ' ',
                               'LDDLFLAGS' => '-mdll -s -L"C:\\strawberry\\perl\\lib\\CORE" -L"C:\\strawberry\\c\\lib"',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'LDLOADLIBS' => 'liboci.a C:\\strawberry\\c\\lib\\libmsvcrt.a C:\\strawberry\\c\\lib\\libmoldname.a C:\\strawberry\\c\\lib\\libkernel32.a C:\\strawberry\\c\\lib\\libuser32.a C:\\strawberry\\c\\lib\\libgdi32.a C:\\strawberry\\c\\lib\\libwinspool.a C:\\strawberry\\c\\lib\\libcomdlg32.a C:\\strawberry\\c\\lib\\libadvapi32.a C:\\strawberry\\c\\lib\\libshell32.a C:\\strawberry\\c\\lib\\libole32.a C:\\strawberry\\c\\lib\\liboleaut32.a C:\\strawberry\\c\\lib\\libnetapi32.a C:\\strawberry\\c\\lib\\libuuid.a C:\\strawberry\\c\\lib\\libws2_32.a C:\\strawberry\\c\\lib\\libmpr.a C:\\strawberry\\c\\lib\\libwinmm.a C:\\strawberry\\c\\lib\\libversion.a C:\\strawberry\\c\\lib\\libodbc32.a C:\\strawberry\\c\\lib\\libodbccp32.a',
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'MACROSTART' => '',
                               'XS_VERSION' => '1.23',
                               'MAKEMAKER' => 'C:/strawberry/perl/lib/ExtUtils/MakeMaker.pm',
                               'USEMAKEFILE' => '-f',
                               'RM_RF' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_rf',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'INST_LIBDIR' => '$(INST_LIB)\\DBD',
                               'SITEARCHEXP' => 'C:\\strawberry\\perl\\site\\lib',
                               'ABSTRACT' => 'Oracle database driver for the DBI module',
                               'INST_MAN1DIR' => 'blib\\man1',
                               'MAN3EXT' => '3',
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'MAKE' => 'dmake',
                               'FULL_AR' => '',
                               'FULLPERL' => 'C:\\strawberry\\perl\\bin\\perl.exe',
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'exe_ext',
                                             'full_ar',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'DESTDIR' => '',
                               'MAN1PODS' => {},
                               'INSTALLSITEBIN' => 'C:\\strawberry\\perl\\bin',
                               'CHMOD' => '$(ABSPERLRUN) -MExtUtils::Command -e chmod',
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'OBJ_EXT' => '.o',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                               'TARFLAGS' => 'cvf',
                               'PERL_INC' => 'C:\\strawberry\\perl\\lib\\CORE',
                               'HAS_LINK_CODE' => 1,
                               'INSTALLPRIVLIB' => 'C:\\strawberry\\perl\\lib',
                               'SITELIBEXP' => 'C:\\strawberry\\perl\\site\\lib',
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'VENDORLIBEXP' => '',
                               'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"11.1.0.7\\"',
                               'FULLEXT' => 'DBD\\Oracle',
                               'MAKEFILE' => 'Makefile',
                               'PL_FILES' => {
                                               'ora_explain.PL' => 'ora_explain'
                                             },
                               'VENDORARCHEXP' => '',
                               'MM_VERSION' => '6.48',
                               'INSTALLSCRIPT' => 'C:\\strawberry\\perl\\bin',
                               'CC' => 'gcc',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'DLEXT' => 'dll',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) "-MExtUtils::Command" -e eqtime',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'VERBINST' => 0,
                               'TAR' => 'tar',
                               'ABSPERL' => '$(PERL)',
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)\\$(BASEEXT)$(LIB_EXT)',
                               'DISTVNAME' => 'DBD-Oracle-1.23',
                               'ABSTRACT_FROM' => 'Oracle.pm',
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'INST_AUTODIR' => '$(INST_LIB)\\auto\\$(FULLEXT)',
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.48 (Revision: 64800) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[Oracle.pm]',
                                             '#     AUTHOR => q[Tim Bunce (dbi-users@perl.org)]',
                                             '#     DEFINE => q[ -Wall -Wno-comment -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"11.1.0.7\\"]',
                                             '#     DIR => []',
                                             '#     EXE_FILES => [q[ora_explain]]',
                                             '#     INC => q[-IC:/instantclient_11_1/sdk/include -IC:/instantclient_11_1/rdbms/demo -IC:\\strawberry\\perl\\site\\lib\\auto\\DBI]',
                                             '#     LIBS => [q[-LC:/strawberry/cpan/build/DBD-Oracle-1.23-7X_huJ -loci]]',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[1.51] }',
                                             '#     VERSION_FROM => q[Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { DIST_DEFAULT=>q[clean distcheck disttest tardist], COMPRESS=>q[gzip -v9], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'MAP_TARGET' => 'perl',
                               'INSTALLMAN3DIR' => 'none',
                               'PERLPREFIX' => 'C:\\strawberry\\perl',
                               'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                               'INC' => '-IC:/instantclient_11_1/sdk/include -IC:/instantclient_11_1/rdbms/demo -IC:\\strawberry\\perl\\site\\lib\\auto\\DBI',
                               'LDFLAGS' => '-s -L"C:\\strawberry\\perl\\lib\\CORE" -L"C:\\strawberry\\c\\lib"',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'INSTALLVENDORMAN1DIR' => '',
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'CI' => 'ci -u',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)\\DBD',
                               'OBJECT' => '$(O_FILES)',
                               'NAME_SYM' => 'DBD_Oracle',
                               'RANLIB' => 'rem',
                               'DIRFILESEP' => '\\\\',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'INSTALLVENDORBIN' => '',
                               'COMPRESS' => 'gzip --best',
                               'SUFFIX' => '.gz',
                               'MAN1EXT' => '1',
                               'PERL_LIB' => 'C:\\strawberry\\perl\\lib',
                               'ECHO' => '$(ABSPERLRUN) -l -e "print qq{{@ARGV}" --',
                               'EXPORT_LIST' => '$(BASEEXT).def',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)\\$(BASEEXT).bs',
                               'MV' => '$(ABSPERLRUN) -MExtUtils::Command -e mv',
                               'OSVERS' => '5.1',
                               'LD_RUN_PATH' => '',
                               'MKPATH' => '$(ABSPERLRUN) "-MExtUtils::Command" -e mkpath',
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'OSNAME' => 'MSWin32',
                               'AR' => 'ar',
                               'O_FILES' => [
                                              'Oracle.o',
                                              'dbdimp.o',
                                              'oci8.o'
                                            ],
                               'FIXIN' => 'pl2bat.bat',
                               'DIST_DEFAULT' => 'tardist',
                               'SKIPHASH' => {},
                               'NOOP' => 'rem',
                               'PERL_ARCHLIB' => 'C:\\strawberry\\perl\\lib',
                               'VERSION_SYM' => '1_23',
                               'VERSION_MACRO' => 'VERSION',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist',
                               'MM_REVISION' => 64800,
                               'RM_F' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_f',
                               'LIBC' => '-lmsvcrt',
                               'UNINST' => 0,
                               'PERLRUN' => '$(PERL)',
                               'LINKTYPE' => 'dynamic',
                               'INSTALLVENDORLIB' => '',
                               'DEV_NULL' => '> NUL',
                               'DLSRC' => 'dl_win32.xs',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)\\auto\\$(FULLEXT)',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'MACROEND' => '',
                               'ARGS' => {
                                           'NAME' => 'DBD::Oracle',
                                           'INC' => '-IC:/instantclient_11_1/sdk/include -IC:/instantclient_11_1/rdbms/demo -IC:\\strawberry\\perl\\site\\lib\\auto\\DBI',
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"11.1.0.7\\"',
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'OBJECT' => '$(O_FILES)',
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                                           'ABSTRACT_FROM' => 'Oracle.pm',
                                           'VERSION_FROM' => 'Oracle.pm',
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'}
                                         },
                               'CP' => '$(ABSPERLRUN) -MExtUtils::Command -e cp',
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)',
                               'INST_LIB' => 'blib\\lib',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)\\$(DLBASE).$(DLEXT)',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'INSTALLSITEMAN1DIR' => '$(INSTALLMAN1DIR)',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e "install({{@ARGV}, \'$(VERBINST)\', 0, \'$(UNINST)\');" --',
                               'DLBASE' => '$(BASEEXT)',
                               'INST_MAN3DIR' => 'blib\\man3',
                               'CCCDLFLAGS' => ' ',
                               'INSTALLSITEARCH' => 'C:\\strawberry\\perl\\site\\lib',
                               'PMLIBPARENTDIRS' => [
                                                      'lib'
                                                    ],
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'DESTINSTALLSITESCRIPT' => '$(DESTDIR)$(INSTALLSITESCRIPT)',
                               'SHAR' => 'shar',
                               'PERLMAINCC' => '$(CC)',
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'NAME' => 'DBD::Oracle',
                               'PARENT_NAME' => 'DBD',
                               'INSTALLSITELIB' => 'C:\\strawberry\\perl\\site\\lib',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'ZIP' => 'zip',
                               'VERSION_FROM' => 'Oracle.pm',
                               'SITEPREFIX' => 'C:\\strawberry\\perl\\site',
                               'INSTALLVENDORSCRIPT' => '',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'PERL' => 'C:\\strawberry\\perl\\bin\\perl.exe',
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'NOECHO' => '@',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'PERM_RW' => 644,
                               'UMASK_NULL' => 'umask 0',
                               'DOC_INSTALL' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e perllocal_install',
                               'TOUCH' => '$(ABSPERLRUN) -MExtUtils::Command -e touch',
                               'LD' => 'g++',
                               'PERL_SRC' => undef,
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'ZIPFLAGS' => '-r',
                               'DISTNAME' => 'DBD-Oracle',
                               'INST_BIN' => 'blib\\bin',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'VENDORPREFIX' => '',
                               'LDFROM' => '$(OBJECT)',
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'PREFIX' => '$(SITEPREFIX)',
                               'INSTALLDIRS' => 'site',
                               'INST_ARCHLIB' => 'blib\\arch',
                               'PERL_ARCHIVE' => '$(PERL_INC)\\libperl510.a',
                               'INSTALLVENDORARCH' => '',
                               'INSTALLBIN' => 'C:\\strawberry\\perl\\bin',
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'INSTALLSITEMAN3DIR' => '$(INSTALLMAN3DIR)',
                               'PERL_ARCHIVE_AFTER' => '',
                               'MAN3PODS' => {},
                               'LIBPERL_A' => 'libperl.a',
                               'INSTALLARCHLIB' => 'C:\\strawberry\\perl\\lib',
                               'LIB_EXT' => '.a',
                               'AR_STATIC_ARGS' => 'cr',
                               'INSTALLVENDORMAN3DIR' => '',
                               'EXE_EXT' => '.exe',
                               'EXTRALIBS' => 'liboci.a C:\\strawberry\\c\\lib\\libmsvcrt.a C:\\strawberry\\c\\lib\\libmoldname.a C:\\strawberry\\c\\lib\\libkernel32.a C:\\strawberry\\c\\lib\\libuser32.a C:\\strawberry\\c\\lib\\libgdi32.a C:\\strawberry\\c\\lib\\libwinspool.a C:\\strawberry\\c\\lib\\libcomdlg32.a C:\\strawberry\\c\\lib\\libadvapi32.a C:\\strawberry\\c\\lib\\libshell32.a C:\\strawberry\\c\\lib\\libole32.a C:\\strawberry\\c\\lib\\liboleaut32.a C:\\strawberry\\c\\lib\\libnetapi32.a C:\\strawberry\\c\\lib\\libuuid.a C:\\strawberry\\c\\lib\\libws2_32.a C:\\strawberry\\c\\lib\\libmpr.a C:\\strawberry\\c\\lib\\libwinmm.a C:\\strawberry\\c\\lib\\libversion.a C:\\strawberry\\c\\lib\\libodbc32.a C:\\strawberry\\c\\lib\\libodbccp32.a',
                               'PERM_RWX' => 755,
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'DESTINSTALLVENDORSCRIPT' => '$(DESTDIR)$(INSTALLVENDORSCRIPT)',
                               'BASEEXT' => 'Oracle',
                               'TEST_F' => '$(ABSPERLRUN) -MExtUtils::Command -e test_f',
                               'PM' => {
                                         'Oracle.pm' => '$(INST_LIB)\\DBD\\Oracle.pm',
                                         'oraperl.ph' => '$(INST_LIB)/oraperl.ph',
                                         'lib/DBD/Oracle/Object.pm' => 'blib\\lib\\DBD\\Oracle\\Object.pm',
                                         'Oraperl.pm' => '$(INST_LIB)/Oraperl.pm',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib\\lib\\DBD\\Oracle\\GetInfo.pm',
                                         'mk.pm' => '$(INST_LIB)\\DBD\\mk.pm'
                                       },
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'PERL_CORE' => 0,
                               'INSTALLMAN1DIR' => 'none',
                               'SO' => 'dll',
                               'VERSION' => '1.23',
                               'DIST_CP' => 'best',
                               'INST_SCRIPT' => 'blib\\script',
                               'UNINSTALL' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e uninstall'
                             }, 'PACK001' );
