<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oozie"
    nsURI="http://www.talend.org/oozie" nsPrefix="TalendOOZIE">
  <eClassifiers xsi:type="ecore:EClass" name="OozieConnection" eSuperTypes="../../org.talend.repository.hadoopcluster/model/hadoopcluster.ecore#//HadoopSubConnection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oozieEndPoind" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oozieVersion" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableKerberos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OozieConnectionItem" eSuperTypes="../../org.talend.repository.hadoopcluster/model/hadoopcluster.ecore#//HadoopSubConnectionItem"/>
</ecore:EPackage>
