package org.talend.hadoop.distribution.emr5150;

public enum EMR5150Constant {
    HDFS_MODULE_GROUP("HDFS-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    MAPREDUCE_MODULE_GROUP("MAPREDUCE-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    HBASE_MODULE_GROUP("HBASE-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    HIVE_MODULE_GROUP("HIVE-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SQOOP_MODULE_GROUP("SQOOP-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_MODULE_GROUP("SPARK2-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    HIVE_HBASE_MODULE_GROUP("HIVE-HBASE-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    MAPREDUCE_PARQUET_MRREQUIRED_MODULE_GROUP("MAPREDUCE-PARQUET-LIB-MRREQUIRED-EMR_5_15_0"), //$NON-NLS-1$
    MAPREDUCE_AVRO_MRREQUIRED_MODULE_GROUP("MAPREDUCE-AVRO-LIB-MRREQUIRED-EMR_5_15_0"), //$NON-NLS-1$
    SPARK_DYNAMODB_MRREQUIRED_MODULE_GROUP("SPARK-DYNAMODB-LIB-MRREQUIRED-EMR_5_15_0"), //$NON-NLS-1$
    SPARK_PARQUET_MRREQUIRED_MODULE_GROUP("SPARK-PARQUET-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_KINESIS_MRREQUIRED_MODULE_GROUP("SPARK-KINESIS-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_KAFKA_ASSEMBLY_MRREQUIRED_MODULE_GROUP("SPARK-KAFKA-ASSEMBLY-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_KAFKA_AVRO_MRREQUIRED_MODULE_GROUP("SPARK-KAFKA-AVRO-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_KAFKA_CLIENT_MRREQUIRED_MODULE_GROUP("SPARK-KAFKA-CLIENT-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    S3_MODULE_GROUP("S3-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_AZURE_MRREQUIRED_MODULE_GROUP("SPARK-AZURE-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    GRAPHFRAMES_MODULE_GROUP("GRAPHFRAMES-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_HIVE_MRREQUIRED_MODULE_GROUP("SPARK-HIVE-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SPARK_FLUME_MRREQUIRED_MODULE_GROUP("SPARK-FLUME-LIB-MRREQUIRED-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    WEBHDFS_MODULE_GROUP("WEBHDFS-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SQOOP_PARQUET_MODULE_GROUP("SQOOP-PARQUET-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SQOOP_AVRO_MODULE_GROUP("SQOOP-AVRO-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SQOOP_SEQUENCE_MODULE_GROUP("SQOOP-SEQUENCE-LIB-EMR_5_15_0_LATEST"), //$NON-NLS-1$
    SQOOP_TEXT_MODULE_GROUP("SQOOP-TEXT-LIB-EMR_5_15_0_LATEST"); //$NON-NLS-1$

    private String mModuleName;

    EMR5150Constant(String moduleName) {
        this.mModuleName = moduleName;
    }

    public String getModuleName() {
        return this.mModuleName;
    }
}
